
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/airline"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airline
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:  # Adicione esta seção
      test: ["CMD-SHELL", "pg_isready -U user -d airline"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:  # Adicione esta seção
  backend-network:
    driver: bridge