
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airline-backend
  template:
    metadata:
      labels:
        app: airline-backend
    spec:
      containers:
        - name: app
          image: airline-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/airline"
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: airline
              resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
              